workflow:
  rules:
    # These 3 rules from https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
    # Run on merge requests
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on tags
    - if: $CI_COMMIT_TAG
    # Run when called from an upstream pipeline https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html?tab=Multi-project+pipeline#use-rules-to-control-downstream-pipeline-jobs
    - if: $CI_PIPELINE_SOURCE == 'pipeline'
    - if: $CI_PIPELINE_SOURCE == 'parent-child'
    # Run on commits to the default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # The last rule above blocks manual and scheduled pipelines on non-default branch. The rule below allows them:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # Run if triggered from Web using 'Run Pipelines'
    - if: $CI_PIPELINE_SOURCE == "web"
    # Run if triggered from WebIDE
    - if: $CI_PIPELINE_SOURCE == "webide"

.downstream-base:
  variables:
    # So downstream plugins know which .gitlab-ci.yml include to use.
    _GITLAB_TEMPLATES_REPO: $CI_PROJECT_PATH
    _GITLAB_TEMPLATES_REF: $CI_COMMIT_REF_NAME
  rules:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#predefined-variables-for-merge-request-pipelines
    - if: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
      variables:
        _GITLAB_TEMPLATES_REPO: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
  stage: test
  # Manual is needed because one must be a maintainer in the project below to run a pipeline there.
  when: manual

keycdn:
  extends: .downstream-base
  trigger:
    strategy: depend
    project: project/keycdn
    branch: 8.x-1.x

# For Nightwatch testing.
decoupled_pages:
  extends: .downstream-base
  trigger:
    strategy: depend
    project: project/decoupled_pages
    branch: 8.x-1.x